### ISSUE TITLE
Failed to connect to mongo MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"

### ISSUE THREAD

**Issue by ownzi** [4350pChris/slack-vuesualizer#250]
Hey. I'm trying to run the app on a headless CentOS 9 VM.

It looks like its running and I upload the file, choose the channels, click next and the first upload is "workspace" which fails.

Looking at the npm output I see the below:

[root@scv1 slack-vuesualizer-1.0.4]# npm run preview

slack-vuesualizer@1.0.0 preview
nuxt preview

Nuxi 3.2.3                                                                                                                                                                                        10:09:36
Node.js version: 16.18.1                                                                                                                                                                        10:09:36
Preset: node-server                                                                                                                                                                             10:09:36
Working dir: .output                                                                                                                                                                            10:09:36
Loading .env. This will not be loaded when running the server in production.                                                                                                                    10:09:36
Starting preview command: node ./server/index.mjs                                                                                                                                               10:09:36
                                                                                                                                                                                                  10:09:36
Listening http://[::]:3000
Failed to connect to mongo MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/home/user/slack-vuesualizer-1.0.4/.output/server/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/home/user/slack-vuesualizer-1.0.4/.output/server/node_modules/mongodb/lib/connection_string.js:204:17)
    at new MongoClient (/home/user/slack-vuesualizer-1.0.4/.output/server/node_modules/mongodb/lib/mongo_client.js:46:63)
    at Function.connect (/home/user/slack-vuesualizer-1.0.4/.output/server/node_modules/mongodb/lib/mongo_client.js:231:24)
    at fullClient (file:///home/user/slack-vuesualizer-1.0.4/.output/server/chunks/mongo.mjs:9:39)
    at mongo (file:///home/user/slack-vuesualizer-1.0.4/.output/server/chunks/mongo.mjs:18:10)
    at file:///home/user/slack-vuesualizer-1.0.4/.output/server/chunks/index.post.mjs:31:20
    at file:///home/user/slack-vuesualizer-1.0.4/.output/server/node_modules/h3/dist/index.mjs:1140:47
    at async Object.handler (file:///home/user/slack-vuesualizer-1.0.4/.output/server/node_modules/h3/dist/index.mjs:1196:19)
    at async Server.toNodeHandle (file:///home/user/slack-vuesualizer-1.0.4/.output/server/node_modules/h3/dist/index.mjs:1271:7)
[nuxt] [request error] [unhandled] [500] Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
  at new ConnectionString (./server/node_modules/mongodb-connection-string-url/lib/index.js:86:19)  
  at parseOptions (./server/node_modules/mongodb/lib/connection_string.js:204:17)  
  at new MongoClient (./server/node_modules/mongodb/lib/mongo_client.js:46:63)  
  at Function.connect (./server/node_modules/mongodb/lib/mongo_client.js:231:24)  
  at fullClient (./server/chunks/mongo.mjs:9:39)  
  at mongo (./server/chunks/mongo.mjs:18:10)  
  at ./server/chunks/index.post.mjs:31:20  
  at ./server/node_modules/h3/dist/index.mjs:1140:47  
  at async Object.handler (./server/node_modules/h3/dist/index.mjs:1196:19)  
  at async Server.toNodeHandle (./server/node_modules/h3/dist/index.mjs:1271:7)

Which is strange because the .env file should be correct:

`[root@scv1 slack-vuesualizer-1.0.4]# cat database.env 
NUXT_MONGODB_URI=mongodb://localhost:27017
NUXT_CANONICAL_HOST=http://localhost:3000
`

I'm not sure if the platform can run if mongodb has no authorisation configured.

Thanks.

**Comment by 4350pChris** [comment]
I think the problem might be that your file is called `database.env` when it should just be called `.env`. That probable leads to it not being included and therefore the connection string being empty / undefined. Could you try renaming it and trying again?

**Comment by ownzi** [comment]
YEP. That was it... Feel kinda stupid now. :D Thanks!

**Comment by 4350pChris** [comment]
Glad I could help. Here's the related docs btw https://vitejs.dev/guide/env-and-mode.html#env-files

**Comment by 4350pChris** [comment]
Check your .env file for the correct connection string.
